### ISSUE TITLE
dont do anything for me

### ISSUE THREAD

**Issue by dogigijgig** [Antsbatscats/Python-File-Stealer#1]
i ran it and changed extentions and changed webhook and when i ran it my screen flashes black for a second and dosent send any files

**Comment by Antsbatscats** [comment]
Can you show me what your code looks like. 
Its possible that the way u changed the extension has made it so that no file is accepted. That's why the screen could be turning black for just a second, its made so that once the upload is over the screen turns back on so that is possibility.

**Comment by Antsbatscats** [comment]
Also what variation of the code are you using, the functional one is stealer8.py The older variations don't work or malfunction a lot.
